fix comfyui
fixes following error:
RuntimeError: cuDNN Frontend error: No valid engine configs for Matmul_MUL_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_

which is thrown from within this function:
https://github.com/comfyanonymous/ComfyUI/blob/bcbd7884e3af5ee8b6ab848da2a3123f247d6114/comfy/ops.py#L47

and originates from:
https://github.com/NVIDIA/cudnn-frontend/blob/1a7b4b78db44712fb9707d21cd2e3179f1fd88b8/include/cudnn_frontend/plans.h#L90